// <auto-generated />
namespace BikeRent.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DbInit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DbInit));
        
        string IMigrationMetadata.Id
        {
            get { return "202101250950576_DbInit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
